local psy_immune_factions = {
	["monolith"] = true,
	["isg"] = true,
	["greh"] = true,
	["zombied"] = true
}

blacklist_helper.ShouldBlacklistNorth = function ()
    local playerFaction = get_actor_true_community()
	
	if
		(has_alife_info("yan_labx16_switcher_primary_off"))
		or
		(psy_immune_factions[playerFaction] or has_alife_info("story_mode_disabled"))
	then
		return false
	end

	return true
end